// * React Native
import { Platform, StyleSheet } from 'react-native';
import { darkTheme, lightTheme } from './utils';

export const styles = StyleSheet.create({
  textInput: {
    backgroundColor: lightTheme.colors.background, // theme.colors.background, //'#efebe9',
    borderColor: '#4e342e',
    borderLeftColor: '#4e342e',
    borderCurve: 'continuous',
    borderTopWidth: Platform.OS === 'ios' ? 0.2 : 0.5,
    borderBottomWidth: 0.1,
    borderLeftWidth: 0.5,
    borderRightWidth: 0.5,
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
    marginBottom: 20,
    overflow: 'hidden',
  },
  darkTextInput: {
    backgroundColor: darkTheme.colors.inputs.background, // theme.colors.background, //'#efebe9',
    borderColor: darkTheme.colors.inputs.border,
    borderLeftColor: darkTheme.colors.inputs.border,
    borderCurve: 'continuous',
    borderTopWidth: Platform.OS === 'ios' ? 0.2 : 0.5,
    borderBottomWidth: 0.1,
    borderLeftWidth: 0.5,
    borderRightWidth: 0.5,
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
    marginBottom: 20,
    overflow: 'hidden',
  },
  lightTextInput: {
    backgroundColor: lightTheme.colors.inputs.background,
    borderColor: '#4e342e',
    borderLeftColor: '#4e342e',
    borderCurve: 'continuous',
    borderTopWidth: Platform.OS === 'ios' ? 0.2 : 0.5,
    borderBottomWidth: 0.1,
    borderLeftWidth: 0.5,
    borderRightWidth: 0.5,
    borderTopStartRadius: 10,
    borderTopEndRadius: 10,
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
    marginBottom: 20,
    overflow: 'hidden',
  },
  helperText: { alignSelf: 'flex-end', marginTop: -22, marginRight: -8 },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  listItemImage: {
    height: 45,
    width: 45,
    marginRight: 10,
    borderRadius: 10,
  },
});
